#!/usr/bin/env bash

# 学习shell 数组
# 定义数组
nums=(1 3 5)

# 给数组元素赋值
nums[1]=33
# 增加一个元素到数组中
nums[3]=7

# 获取数组中的某个元素
echo ${nums[1]}

# 获取数组中的所有元素
echo ${nums[*]}

# 同字符串一样，通过 # 获取数组的长度
# echo ${#str}
echo ${#nums[*]}

# 删除数组元素
unset nums[2]